# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 00:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tonerecorder', '0015_recordedsyllable_audio_mp3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('discard', models.BooleanField()),
                ('button_sounds', models.BooleanField()),
                ('background_hum', models.BooleanField()),
                ('background_noise', models.BooleanField()),
                ('other', models.CharField(max_length=80, null=True)),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
    ]
